### ISSUE TITLE
multiple thermostats?

### ISSUE THREAD

**Issue by dominikfe** [algirdasc/hass-components#12]
Hi!
With one single thermostat my config works. But when I add another thermostat HA only uses the last entry. How do I have to structure the entry in configuration.yaml?

`climate:
  platform: floureon
  name: Thermostat
  mac: 34:EA:34:9F:xx:xx
  host: 192.168.10.55
  use_external_temp: false

climate:
  platform: floureon
  name: Flur EG
  mac: 34:EA:34:77:xx:xx
  host: 192.168.10.85
  use_external_temp: false`

**Comment by algirdasc** [comment]
You duplicated `climate:` key. Your configuration should look like this:

```
climate:
  - platform: floureon
    name: Thermostat
    mac: 34:EA:34:9F:xx:xx
    host: 192.168.10.55
    use_external_temp: false

  - platform: floureon
    name: Flur EG
    mac: 34:EA:34:77:xx:xx
    host: 192.168.10.85
   use_external_temp: false
```
